### ISSUE TITLE
Bug in the windows loader when loading Aspack packed binaries 

### ISSUE THREAD

**Issue by MennaEssa** [carbonblack/binee#23]
Hello , 
I was testing binee with multiple packers and noticed that it fails to load samples packed with ASPack with the following error

`
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x553c3a]
goroutine 1 [running]:
github.com/carbonblack/binee/pefile.(*PeFile).ImageBase(...)
    /bineedev/go/src/github.com/carbonblack/binee/pefile/pefile.go:197
github.com/carbonblack/binee/windows.(*WinEmulator).initPe(0xc0000da900, 0x0, 0x7ffcc52dceda, 0x39, 0x4, 0x4, 0xc00008a640, 0x1, 0x1, 0x400, ...)
    /bineedev/go/src/github.com/carbonblack/binee/windows/loader.go:731 +0x3a
github.com/carbonblack/binee/windows.New(0x7ffcc52dceda, 0x39, 0x4, 0x4, 0xc00008a640, 0x1, 0x1, 0x1, 0x0, 0x0, ...)
    /bineedev/go/src/github.com/carbonblack/binee/windows/winemulator.go:284 +0x2133
main.main()
    /bineedev/go/src/github.com/carbonblack/binee/main.go:176 +0x604
main.main() `

I discussed the issue with Kyle on slack and he agreed that there is a bug in the pe parser
Here is the binary that reproduces the error : https://www.virustotal.com/gui/file/8d3c9d450922299dd79fc509c7aa789b12df5c15f309fc1efa2a59cbf020cd0b/detection

**Comment by MennaEssa** [comment]
after some debugging it turns out .apack section has size zero at EOF so the read operation fails and crashes the emulator
I tested the following proposed fix in pefile.go line 334
```

if _, err = r.Read(raw); err != nil {
            if err == io.EOF {
                pe.Sections[i].Raw = nil
                continue
            }
            return nil, errors.New(fmt.Sprintf("Error reading bytes at offset[0x%x] in section[%s] of file %s: %v", pe.Sections[i].Offset, pe.Sections[i].Name, path, err))
        }
```
